pipeline {
    agent any
    stages {
        stage('Initialize') {
            steps {
                echo "Initializing pipeline..."
            }
        }

        stage('Checkout Code') {
            steps {
                echo "Cloning repository..."
            }
        }

        stage('Build') {
            steps {
                echo "Building the application..."
            }
        }

        stage('Test') {
            steps {
                echo "Executing tests..."
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying application..."
            }
        }
    }
}
//Testing Webhook
